#
# This file was automatically generated by ReFrame based on 'setup_files/settings.py'.  # noqa: E501
# System configuration file for ella, based on 'setup_files/settings.py'
#


site_configuration = {
    'systems': [
        {
            'name': 'ella',
            'descr': 'Ella',
            'hostnames': ['ella-n001', 'ella-n002', 'ella-n003', 'ella-n004', 'ella-n005', 'ella-n006', 'ella-n007', 'ella-n008'],
            'modules_system': 'lmod',
            'partitions': [
                {
                    'name': 'login',
                    'scheduler': 'local',
                    'launcher': 'local',
                    'modules': [],
                    'access': [],
                    'environs': ['PrgEnv-gnu'],
                    'descr': 'Ella login node',
                    'max_jobs': 1,
                },
                {
                    'name': 'gpu',
                    'scheduler': 'slurm',
                    'launcher': 'srun',
                    'modules': [],
                    'access': ['--partition=gpu'],
                    'max_jobs': 1,
                    'environs': ['PrgEnv-gnu'],
                    'descr': 'Ella GPU partition',
                },
            ]
        },
    ],
    'environments': [
        {
            'name': 'PrgEnv-gnu',
            'target_systems': ['ella'],
            'modules': [],
            'cc': 'gcc',
            'cxx': 'g++',
        }
    ],
    'logging': [
        {
            'level': 'debug',
            'handlers': [
                {
                    'type': 'file',
                    'name': 'reframe.log',
                    'level': 'debug',
                    'format': '[%(asctime)s] %(levelname)s: %(check_name)s: %(message)s',  # noqa: E501
                    'append': False
                },
                {
                    'type': 'stream',
                    'name': 'stdout',
                    'level': 'info',
                    'format': '%(message)s'
                },
                {
                    'type': 'file',
                    'name': 'reframe.out',
                    'level': 'info',
                    'format': '%(message)s',
                    'append': False
                }
            ],
            'handlers_perflog': [
                {
                    'type': 'filelog',
                    'prefix': '%(check_system)s/%(check_partition)s',
                    'level': 'info',
                    'format': '%(asctime)s|reframe %(version)s|%(check_info)s|jobid=%(check_jobid)s|%(check_perf_var)s=%(check_perf_value)s|ref=%(check_perf_ref)s (l=%(check_perf_lower_thres)s, u=%(check_perf_upper_thres)s)',  # noqa: E501
                    'append': True
                }
            ]
        }
    ],
    'modes': [
        {
            'name': 'maintenance',
            'options': [
                '--exec-policy=async',
                '--reservation=maintenance',
                '--save-log-files',
                '--tag=acceptance',
                '--timestamp=%F_%H-%M-%S'
            ]
        },
    ],
    'general': [
        {
            'check_search_path': [
                'checks/'
            ],
            'check_search_recursive': True
        }
    ]
}
