#
# This file was automatically generated by ReFrame based on 'setup_files/settings.py'.  # noqa: E501
#


site_configuration = {
    'systems': [
        {
            'name': 'system',
            'descr': 'Some description',
            'hostnames': [
                'system-01', 
            ],
            'modules_system': 'lmod',
            'partitions': [
                {
                    'name': 'login',
                    'scheduler': 'local',
                    'modules': [],
                    'access': [],
                    'environs': [
                        'PrgEnv-cray',
                        'PrgEnv-gnu',
                        'PrgEnv-aocc'
                    ],
                    'descr': 'Login nodes',
                    'max_jobs': 1,
                    'launcher': 'local'
                },
                {
                    'name': 'work',
                    'scheduler': 'slurm',
                    'modules': [],
                    'access': [],
                    'environs': [
                        'PrgEnv-cray',
                        'PrgEnv-gnu',
                        'PrgEnv-aocc'
                    ],
                    'descr': 'Standard compute nodes',
                    'max_jobs': 32,
                    'launcher': 'srun'
                },
            ]
        },
    ],
    'environments': [
        {
            'name': 'PrgEnv-cray',
            'modules': [
                'PrgEnv-cray',
                'cray-mpich'
            ],
            'variables': [
                [
                    'CRAYPE_LINK_TYPE',
                    'dynamic'
                ]
            ]
        },
        {
            'name': 'PrgEnv-gnu',
            'modules': [
                'PrgEnv-gnu',
                'cray-mpich'
            ],
            'variables': [
                [
                    'CRAYPE_LINK_TYPE',
                    'dynamic'
                ]
            ]
        },
        {
            'name': 'PrgEnv-aocc',
            'modules': [
                'PrgEnv-aocc',
                'cray-mpich'
            ],
            'variables': [
                [
                    'CRAYPE_LINK_TYPE',
                    'dynamic'
                ]
            ]
        },
    ],
    'logging': [
        {
            'level': 'debug',
            'handlers': [
                {
                    'type': 'file',
                    'name': 'reframe.log',
                    'level': 'debug',
                    'format': '[%(asctime)s] %(levelname)s: %(check_name)s: %(message)s',  # noqa: E501
                    'append': False
                },
                {
                    'type': 'stream',
                    'name': 'stdout',
                    'level': 'info',
                    'format': '%(message)s'
                },
                {
                    'type': 'file',
                    'name': 'reframe.out',
                    'level': 'info',
                    'format': '%(message)s',
                    'append': False
                }
            ],
            'handlers_perflog': [
                {
                    'type': 'filelog',
                    'prefix': '%(check_system)s/%(check_partition)s',
                    'level': 'info',
                    'format': '%(asctime)s|reframe %(version)s|%(check_info)s|jobid=%(check_jobid)s|%(check_perf_var)s=%(check_perf_value)s|ref=%(check_perf_ref)s (l=%(check_perf_lower_thres)s, u=%(check_perf_upper_thres)s)',  # noqa: E501
                    'append': True
                }
            ]
        }
    ],
    'modes': [
        {
            'name': 'maintenance',
            'options': [
                '--exec-policy=async',
                '--reservation=maintenance',
                '--save-log-files',
                '--tag=acceptance',
                '--timestamp=%F_%H-%M-%S'
            ]
        },
    ],
    'general': [
        {
            'check_search_path': [
                'checks/'
            ],
            'check_search_recursive': True
        }
    ]
}
